from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('materials/', views.materials, name='materials'),
    path('addnote/', views.addnote, name='addnote'),
    path('myclass/', views.myclass, name='myclass'),
    path('profile/', views.profile, name='profile'),

    path('class/8/', views.class_eight, name='class_eight'),
    path('class/9/', views.class_nine, name='class_nine'),
    path('class/10/', views.class_ten, name='class_ten'),
    path('class/11/', views.class_eleven, name='class_eleven'),
    path('class/12/', views.class_twelve, name='class_twelve'),

    path('class/8/system/', views.eight, name='eight'),

    path('class/9/system/', views.nine_system, name='nine_system'),
    path('class/9/networks/', views.nine_networks, name='nine_networks'),

    path('class/10/system/', views.ten_system, name='ten_system'),
    path('class/10/networks/', views.ten_networks, name='ten_networks'),

    path('class/11/system/', views.eleven_system, name='eleven_system'),
    path('class/11/networks/', views.eleven_networks, name='eleven_networks'),

    path('class/12/system/', views.twelve_system, name='twelve_system'),
    path('class/12/networks/', views.twelve_networks, name='twelve_networks'),

    path('class/9/networkssubj/', views.nine_networkssubj, name='nine_networkssubj'),
    path('class/9/electrotechnics/', views.nine_electrotechnics, name='nine_electrotechnics'),
    path('class/9/literature/', views.nine_literature, name='nine_literature'),
    path('class/9/chemistry/', views.nine_chemistry, name='nine_chemistry'),
    path('class/9/geography/', views.nine_geography, name='nine_geography'),
    path('class/9/scripts/', views.nine_scripts, name='nine_scripts'),
    path('class/9/history/', views.nine_history, name='nine_history'),
    path('class/9/programming/', views.nine_programming, name='nine_programming'),
    path('class/9/zbut/', views.nine_zbut, name='nine_zbut'),
    path('class/9/gradivni/', views.nine_gradivni, name='nine_gradivni'),
    path('class/9/physycs/', views.nine_physycs, name='nine_physycs'),
    path('class/9/phylosophy/', views.nine_phylosophy, name='nine_phylosophy'),
    path('class/9/russian/', views.nine_russian, name='nine_russian'),
    path('class/9/maths/', views.nine_maths, name='nine_maths'),
    path('class/9/english/', views.nine_english, name='nine_english'),
    path('class/9/biology/', views.nine_biology, name='nine_biology'),
    path('class/9/it/', views.nine_it, name='nine_it'),
    path('class/9/enterprenuering/', views.nine_enterprenuering, name='nine_enterprenuering'),

    path('class/8/biology/', views.eight_biology, name='eight_biology'),
    path('class/8/physycs/', views.eight_physycs, name='eight_physycs'),
    path('class/8/intro_program/', views.eight_intro_program, name='eight_intro_program'),
    path('class/8/literature/', views.eight_literature, name='eight_literature'),
    path('class/8/english/', views.eight_english, name='eight_english'),
    path('class/8/history/', views.eight_history, name='eight_history'),
    path('class/8/intro_special/', views.eight_intro_special, name='eight_intro_special'),
    path('class/8/it/', views.eight_it, name='eight_it'),
    path('class/8/geography/', views.eight_geography, name='eight_geography'),
    path('class/8/chem/', views.eight_chem, name='eight_chem'),
    path('class/8/phylosophy/', views.eight_phylosophy, name='eight_phylosophy'),

    path('class/10/physycs/', views.ten_physycs, name='ten_physycs'),
    path('class/10/history/', views.ten_history, name='ten_history'),
    path('class/10/russian/', views.ten_russian, name='ten_russian'),
    path('class/10/iconomics/', views.ten_iconomics, name='ten_iconomics'),
    path('class/10/literature/', views.ten_literature, name='ten_literature'),
    path('class/10/oop/', views.ten_oop, name='ten_oop'),
    path('class/10/biology/', views.ten_biology, name='ten_biology'),
    path('class/10/maths/', views.ten_maths, name='ten_maths'),
    path('class/10/asd/', views.ten_asd, name='ten_asd'),
    path('class/10/vmks/', views.ten_vmks, name='ten_vmks'),
    path('class/10/gradivni/', views.ten_gradivni, name='ten_gradivni'),
    path('class/10/chem/', views.ten_chem, name='ten_chem'),
    path('class/10/english/', views.ten_english, name='ten_english'),
    path('class/10/geography/', views.ten_geography, name='ten_geography'),
    path('class/10/digital_sch/', views.ten_digital_sch, name='ten_digital_sch'),
    path('class/10/analogy_sch/', views.ten_analogy_sch, name='ten_analogy_sch'),
    path('class/10/phylosophy/', views.ten_phylosophy, name='ten_phylosophy'),
    path('class/10/comp_arch_per_dev/', views.ten_comp_arch_per_dev, name='ten_comp_arch_per_dev'),
    path('class/10/intro_cmr/', views.ten_intro_cmr, name='ten_intro_cmr'),
]