# Generated by Django 6.0.3 on 2026-06-03 19:06

import django.db.models.deletion
import notenet.models
from django.db import migrations, models

def migrate_files_to_material_files(apps, schema_editor):
    Material = apps.get_model('notenet', 'Material')
    MaterialFile = apps.get_model('notenet', 'MaterialFile')
    for material in Material.objects.all():
        if material.file:
            MaterialFile.objects.create(material=material, file=material.file)

class Migration(migrations.Migration):

    dependencies = [
        ('notenet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=notenet.models.material_file_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='notenet.material')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.RunPython(migrate_files_to_material_files, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='material',
            name='file',
        ),
    ]

